#!/bin/bash

# OpenNebula drivers for cxm
# Copyleft 2012 - Nicolas AGIUS <nicolas.agius@lps-it.fr>

###########################################################################
#
# This file is part of cxm.
#
# cxm is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

# Hostname of the OpenNebula frontend managing this node
ONE_HOST="xen0vdi01.preprod.virt.s1.p.fti.net"

# Directory used to store configuration file
CFG_DIR="/etc/xen/vm/"

###########################################################################

# Check syntax
if [ $# -ne 3 ]; then
    echo "Bad parameters." 2>&1
    exit 1
fi

VM_NAME=$1
SRC_HOST=$2
DST_HOST=$3

# Get the vm id
VM_ID=$(sed -nre '/VM_ID/{s/([^[:digit:]]+)//p}' $CFG_DIR/$VM_NAME)

# Tell OpenNebula the vm has been migrated. Oned will try to re-migrate it, but it does'nt matter.
su - oneadmin -c "ssh $ONE_HOST onevm livemigrate $VM_ID $DST_HOST"

# vim: ts=4:sw=4:ai
