#!/bin/bash 

# vmm/cxm - OpenNebula virtual machine manager for cxm
# Copyleft 2012 - Nicolas AGIUS <nicolas.agius@lps-it.fr>
#
# Some part of code are inspired from OpenNebula 
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)

###########################################################################
#
# This file is part of cxm.
#
# cxm is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

DRIVER_PATH=$(dirname $0)

source $DRIVER_PATH/../../scripts_common.sh
source $DRIVER_PATH/../../cxmrc

VM_ID=$3
VM_NAME=$(get_vm_name $VM_ID)

if is_in_cluster; then
	CMD="HOME=/root cxm destroy --quiet $VM_NAME"
else
	CMD="xm destroy $VM_NAME"
fi	

exec_and_log "sudo $CMD" "Could not destroy $VM_NAME"

# Cleanup the autostart link
exec_and_log "sudo rm -f $AUTO_DIR/$VM_NAME" "Could not delete autostart link"

# Just a small sleep, not a loop as 'xm destroy' exit immediately
sleep 1

# vim: ts=4:sw=4:ai
