#!/bin/bash 

# tm/cxm - OpenNebula transfert manager for cxm
# Copyleft 2012 - Nicolas AGIUS <nicolas.agius@lps-it.fr>
#
# Some part of code are inspired from OpenNebula 
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)

###########################################################################
#
# This file is part of cxm.
#
# cxm is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

# DELETE <host:remote_system_ds/disk.i|host:remote_system_ds/> vmid dsid
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

DST=$1
VMID=$2
DSID=$3

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

source $TMCOMMON
source $(dirname $0)/../../cxmrc

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------

DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`

#-------------------------------------------------------------------------------
# Delete files on the remote host
#-------------------------------------------------------------------------------

# Wait few seconds for VM to be shutdown, this is ugly but it's working
sleep 10

if [ `is_disk $DST_PATH` -eq 1 ]; then
    # Disk
    log "Deleting LV $DST_PATH"
    remove_lv $DST_HOST $DST_PATH
else
    # Directory
    remove_all_lv $DST_HOST $DST_PATH

    log "Deleting directory $DST_PATH"

	# Delete configuration file
    ssh_exec_and_log $DST_HOST "sudo rm -f \$(readlink $DST_PATH/deployment.0)" "Error deleting $DST_PATH"

    ssh_exec_and_log $DST_HOST "sudo rm -rf $DST_PATH" "Error deleting $DST_PATH"
	
fi

exit 0

# vim: ts=4:sw=4:ai
